In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

Goal: Read in the iris data set and create a machine learning model to predict the species of flower

Steps:
1. Read in iris data set
2. Split the data
3. Create SVC and GridSearchCV
4. Create param_grid
5. Fit and train
6. Predict
7. Evaluate

First we will import our data set using Seaborn

In [2]:
iris = pd.DataFrame(sns.load_dataset('iris'))
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Now it's time to split our data into training and testing. I am wanting to predict the species, so that column will be my y and my x will be the four columns that define the flower in this data set

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X_train, X_test, y_train, y_test = train_test_split(iris.drop('species',axis=1),iris['species'],test_size=0.4)

I will import the packages needed to create this machine learning model. I am choosing to include a GridSearchCV to improve the accuracy of my model. This will find the best C and gamma paramters for my model

In [5]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

In [6]:
param_grid = {'C':[0.1,1,10,100,1000],'gamma':[1,0.1,0.01,0.001,0.0001]}

In [7]:
grid = GridSearchCV(SVC(),param_grid,verbose=3)

Now I will train my model and figure out the best paramaters for the C and gamma values

In [8]:
grid.fit(X_train,y_train)

Fitting 3 folds for each of 25 candidates, totalling 75 fits
[CV] C=0.1, gamma=1 ..................................................
[CV] ......... C=0.1, gamma=1, score=0.9666666666666667, total=   0.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ........................ C=0.1, gamma=1, score=0.9, total=   0.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ......... C=0.1, gamma=1, score=0.8333333333333334, total=   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ....... C=0.1, gamma=0.1, score=0.9333333333333333, total=   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ....... C=0.1, gamma=0.1, score=0.9666666666666667, total=   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ....... C=0.1, gamma=0.1, score=0.8666666666666667, total=   0.0s
[CV] C=0.1, gamma=0.01 ...............................................
[CV] ...... C=0.

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s



[CV] C=1000, gamma=0.01 ..............................................
[CV] ..... C=1000, gamma=0.01, score=0.9666666666666667, total=   0.0s
[CV] C=1000, gamma=0.01 ..............................................
[CV] ..... C=1000, gamma=0.01, score=0.9333333333333333, total=   0.0s
[CV] C=1000, gamma=0.01 ..............................................
[CV] .................... C=1000, gamma=0.01, score=0.9, total=   0.0s
[CV] C=1000, gamma=0.001 .............................................
[CV] ................... C=1000, gamma=0.001, score=1.0, total=   0.0s
[CV] C=1000, gamma=0.001 .............................................
[CV] .... C=1000, gamma=0.001, score=0.9333333333333333, total=   0.0s
[CV] C=1000, gamma=0.001 .............................................
[CV] ................... C=1000, gamma=0.001, score=0.9, total=   0.0s
[CV] C=1000, gamma=0.0001 ............................................
[CV] .................. C=1000, gamma=0.0001, score=1.0, total=   0.0s
[CV] 

[Parallel(n_jobs=1)]: Done  75 out of  75 | elapsed:    0.2s finished


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [0.1, 1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [9]:
grid.best_params_

{'C': 1, 'gamma': 1}

Now I have trained my model it's time to make the predictions

In [10]:
grid_predictions = grid.predict(X_test)

In [11]:
from sklearn.metrics import classification_report,confusion_matrix

In [12]:
print(confusion_matrix(y_test,grid_predictions))
print('\n')
print(classification_report(y_test,grid_predictions))

[[26  0  0]
 [ 0 16  1]
 [ 0  0 17]]


             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        26
 versicolor       1.00      0.94      0.97        17
  virginica       0.94      1.00      0.97        17

avg / total       0.98      0.98      0.98        60



As you can see, the model was very accurate